name: Industrial CI Pipeline

on:
  pull_request:
    branches: [develop, main]
    tags: [ "v*" ]
  push:
    branches:
      - develop
      - main
      - release/*
      - hotfix/*
      - feature/*
      - bugfix/*
env:
  IMAGE_NAME: catalogue
  appVersion:  ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Building application"
          npm install && npm run build

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          echo "Running unit tests"
          npm test || true

  lint_and_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Lint & security scan
        run: |
          echo "Running lint"
          npm run lint || true
          echo "Running security scan"
          npm audit  || true
  App-version:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: APP version package.json
         run: |
           echo "appVersion=$(jq -r .version package.json)" >> $appVersion
           echo "Version is: $appVersion"

  docker-build:
    runs-on: ubuntu-latest
    needs: [build,unit_tests, lint_and_scan]

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=$appVersion,enable={{is_default_branch}}

      # üî® Build image (load locally for scanning)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # üîç Trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$appVersion
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      # üöÄ Push only if scan passes
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $appVersion   
   
  deploy_dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: [unit_tests, lint_and_scan,docker-build]
    steps:
      - name: Deploy to DEV
        run: echo "Deploying to DEV environment"

  deploy_uat:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: [unit_tests, lint_and_scan,docker-build]
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT environment"

  deploy_prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [unit_tests, lint_and_scan,docker-build]
    steps:
      - name: Deploy to PROD
        run: echo "Deploying to PRODUCTION"
